Survey:  # survey link
  URL: 'https://www.surveymonkey.com/r/WJKVKPB'

  # no of questions:
  GROUPS: 10
  # No. of options for each question sequentially:
  OPTIONS: [2, 6, 3, 3, 3, 5, 3, 3, 3, 3]
  # probablities for each choice

  BAIS_DICT: {
      1: [0.3, 0.7], 
      2: [0.5, 0.2, 0.1, 0.2, 0.0, 0.0], 
      3: [0.1, 0.7, 0.2], 
      4: [0.0, 0.9, 0.1], 
      5: [0.8, 0.0, 0.2], 
      6: [0.6, 0.3, 0.1 ,0.0, 0.0],
      7: [0.5, 0.3, 0.2], 
      8: [0.8, 0.1, 0.1], 
      9: [0.6, 0.3, 0.1], 
      10: [0.9, 0.0, 0.1]
  }
  
  # No. of submits
  LOOPS: 30


